server.port=8081

spring.application.name=notification
## DATA SOURCE CONFIGURATIONS
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url= jdbc:postgresql://localhost:5432/mediflow_notification_db
spring.datasource.username=mediflow
spring.datasource.password=password123

## JPA CONFIGURATIONS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

## RABBITMQ CONFIGURATIONS
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest